#!name=Spotify Premium
#!desc=

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/hoang3402/ShadowRocket/main/Js/spotify.js,script-update-interval=0

[MITM]
hostname = %APPEND% spclient.wg.spotify.com