#!name=WPSOffice
#!desc=WPS Office

[MITM]
hostname = %APPEND% *.docer.wps.cn,vipapi.wps.cn,account.wps.cn

[Script]
WPSOffice1=type=http-response,pattern=^https?:\/\/account\.wps\.cn\/api\/v3\/mine\/vips,requires-body=1,script-path=https://raw.githubusercontent.com/hoang3402/ShadowRocket/main/Js/WPSDocerVIPuserCrack.js
WPSOffice2=type=http-request,pattern=^https?:\/\/.+\.(docer.)?wps.cn\/(user\/v1\/vip|android\/mb\/buy|download\/v1\/ios|partner\/invoke\/usable|(api|rank)\/v1(\/mobile\/mb)?\/detail),requires-body=0,script-path=https://raw.githubusercontent.com/hoang3402/ShadowRocket/main/Js/WPSDocerVIPowerCrack.js