#!name=Youtube Premium (IOS>=15)
#!desc=Adblock, phát trong nền, pip

# > Credit
# @Choler & @DivineEngine & @app2smile

[Script]
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence)\?,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/hoang3402/ShadowRocket/main/Js/youtube.request.js
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting)\?,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/hoang3402/ShadowRocket/main/Js/youtube.response.js

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data="https://raw.githubusercontent.com/hoang3402/ShadowRocket/main/Js/blank.txt" header="Content-Type: application/vnd.yt-ump"

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
